### ISSUE TITLE
Remove Signature['Args'] when there are no arguments

### ISSUE THREAD

**Issue by ijlee2** [ijlee2/ember-codemod-args-to-signature#37]
## I would like to see... 🙋‍♀️🙋‍♂️

In `v0.4.1`, the codemod uses the empty object `{}` to mean that there are no arguments. This assumption had been made to ease the initial development.

```ts
interface Signature {
  Args: {};
};
```

Glint, on the other hand, [recommends omitting the `Args` key](https://typed-ember.gitbook.io/glint/environments/ember/component-signatures):

> `Args` represents the arguments your component accepts. Typically this will be an object type mapping the names of your args to their expected type. If no `Args` key is specified, it will be a type error to pass any arguments to your component.

Confirm this recommendation with the Glint team. Afterwards, update the codemod so that we may get:

```ts
interface Signature {};
```

## Why and how 💬

The how is unclear at the moment. There will be a need to refactor code first.

**Comment by mcfiredrill** [comment]
Would be great to have this fix, this is the one issue I'm running into with the codemod.
https://github.com/datafruits/datafruits/pull/1150
Thanks for making this!

**Comment by ijlee2** [comment]
@mcfiredrill Appreciate your feedback! I'll try to work on it later this week/next week.

**Comment by ijlee2** [comment]
I asked the TypeScript/Glint team some months ago, and received a reply that having `Args: {}` is correct when there are no arguments.

> writing `Args: {}` is completely correct (it's the default value if `Args` is unspecified)
> it's just that `typescript-eslint` doesn't like `{}` as a type, because it comes with some footguns

https://discord.com/channels/480462759797063690/786312479620726804/1149362992169893898
